apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pre-pv
  annotations:
    pv.kubernetes.io/provisioned-by: filestore.csi.storage.gke.io
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nconnect=2
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    # Modify this to use the zone, filestore instance and share name.
    volumeHandle: "modeInstance/us-west1-a/nfs/nfss" 
    volumeAttributes:
      ip: 10.133.31.234 # Modify this to Pre-provisioned Filestore instance IP
      volume: nfss # Modify this to Pre-provisioned Filestore instance share name
